name: ryoken_app
description: RYOKEN.AI crypto analytics app (Flutter) — auth, API service, tabs scaffold.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.8.0
  lottie: ^3.1.2

  # Icons / Material 3
  cupertino_icons: ^1.0.6
  firebase_ui_oauth_google: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/loading.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # ← 這裡放你的 logo 圖片路徑
#  adaptive_icon_background: "#0xFF0C0C0C"  # Android 8+ 的背景色
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true